### ISSUE TITLE
ModuleNotFoundError: No module named 'gym_super_mario_bros'

### ISSUE THREAD

**Issue by johnsonkee** [uvipen/Super-mario-bros-PPO-pytorch#1]
When I run the test code "python test.py --world 5 --stage 2", a error occurs. It showed "ModuleNotFoundError: No module named 'gym_super_mario_bros' ", could you mind telling me how to solve it? Thx.

**Comment by xiaosongdeyx001** [comment]
pip install gym-super-mario-bros

**Comment by johnsonkee** [comment]
> pip install gym-super-mario-bros

thank you

**Comment by xiaosongdeyx001** [comment]
next:
ubuntu      sudo apt-get install ffmpeg
Anaconda    conda install ffmpeg
