### ISSUE TITLE
18 stages completed with A3C

### ISSUE THREAD

**Issue by davincibj** [uvipen/Super-mario-bros-PPO-pytorch#2]
In fact, I used your code completed 18/32 stages with A3C, but anyway, 29/32 is much better.
Here is my A3C models you can test:
链接: https://pan.baidu.com/s/1F24higD2uXHn7TeMGRwbjw  密码: mgt3

# Done world and stages
# 1-1,4
# 2-1,2,3,4
# 3-1,2,3,4
# 4-1
# 5-1
# 6-1,3
# 7-1,3
# 8-2,3

**Comment by vietnh1009** [comment]
Thank you for updating me :)

**Comment by vietnh1009** [comment]
@davincibj  Could you send me the trained models directly to my email (nhviet1009@gmail.com), or upload them to google driver then send me the link? I cant down load from the above link.
Thank you in advance

**Comment by davincibj** [comment]
done, pls check your gmail.

**Comment by vietnh1009** [comment]
thank you so much. I got it. I will update readme soon and mention your finding :)

**Comment by vietnh1009** [comment]
@davincibj Hi,
Could you please re-upload the trained models to driver or something like that then resend me the link? The link you sent before, it is not valid anymore. Thank you so much

**Comment by davincibj** [comment]
hi, sent your gmail,  30 days left to download.

**Comment by vietnh1009** [comment]
Hi, thanks so much. I will update readme and mention your finding :100:
