### ISSUE TITLE
Not able to solve any level using provided trained models

### ISSUE THREAD

**Issue by Dhiraj100892** [uvipen/Super-mario-bros-PPO-pytorch#8]
Hi,

I have tried to use the provided models in `trained_models`. Using them agent was able to proceed however couldn't solve the complete level. Either it used to get stuck or die. Were you able to complete the levels using these models?

**Comment by vietnh1009** [comment]
Yes, I just checked again and all of them still work well. Could you clarify how you use these pretrained models?
